import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('A');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Admin@123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('link', { name: 'Branches', exact: true }).click();
  await page.getByRole('button', { name: '+ Add Branch' }).click();
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).click();
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).fill('A');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).fill('Anuradhpaura');
  await page.getByRole('textbox', { name: 'e.g. Kandy, Sri Lanka' }).click();
  await page.getByRole('textbox', { name: 'e.g. Kandy, Sri Lanka' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy, Sri Lanka' }).fill('A');
  await page.getByRole('textbox', { name: 'e.g. Kandy, Sri Lanka' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy, Sri Lanka' }).fill('Anuradhapura');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).click();
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).fill('Anuradhpaura ');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).fill('Anuradhpaura M');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Kandy Central Hub' }).fill('Anuradhpaura Main');
  await page.getByRole('textbox', { name: 'e.g. Mr. Samantha Perera' }).click();
  await page.getByRole('textbox', { name: 'e.g. Mr. Samantha Perera' }).fill('chamsha');
  await page.getByRole('textbox', { name: 'e.g. 0812345678' }).click();
  await page.getByRole('textbox', { name: 'e.g. 0812345678' }).fill('0714558427');
  await page.getByRole('button', { name: 'Add Branch', exact: true }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
});